#!/bin/bash
### post-installation-script example
### set hostname equal to product_name
DEVICE_PRODUCT_NAME=`(cat /sys/devices/virtual/dmi/id/product_name | tr -d '()+-.' | tr -s '  ' | tr ' ' '-' | tr 'A-Z' 'a-z')`
PRESEED=/tmp/preseed_for_${DEVICE_PRODUCT_NAME}.cfg
echo "d-i netcfg/get_hostname string" ${DEVICE_PRODUCT_NAME} > $PRESEED
debconf-set-selections $PRESEED

### post-installation-script example
### change grub timeout to 1 second
sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=1/g' /target/etc/default/grub
in-target update-grub

### To add non-free firmware
cd  ~/spark/cd-root
firmware=https://cdimage.debian.org/cdimage/unofficial/non-free/firmware/`(lsb_release -sc)`/current/firmware.zip
wget $firmware
unzip -n firmware.zip -d ./firmware/
rm firmware.zip
